management:
    security:
        enabled: false
    endpoints:
        web:
            base-path: /https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Migration-Guide#base-path
            #exposure:
                #include: "*"
    graceful.shutdown.enabled: true
security:
    basic:
        enabled: false
    ignored: /**

spring:
    application:
        name: Blood-Bank
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        url: jdbc:sqlserver://DESKTOP-2LF1VAI\SQL2019;databaseName=test;encrypt=false;trustServerCertificate=true
        username: SA
        password: P@ssw0rd
        #url: jdbc:h2:file:./h2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        #driverClassName: org.h2.Driver
        #username: SA
        #password:

    liquibase:
        #change-log: master.xml
        #default-schema: param_achat
        enabled: false
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        database:  SQL_SERVER
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: update
            naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate.default_schema: Blood_Bank
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            hibernate.cache.hazelcast.instance_name: hazelcast
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true


    jackson:
        serialization:
            write-dates-as-timestamps: true
    config:
        use-legacy-processing: true


lang:
    secondary: ar

     
server:
    servlet:
        contextPath: /blood-bank
    port: 9005 
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024 
    
profiles:
    include: no-liquibase

paramService:
    base-uri: http://integration.clinisys.local/parametrage-core
    cabinet: /api/cabinets
    medecin: /api/medecins
    service: /api/services


